// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TTB.BankAccountConsent.Models
{
    [Table("TTBActionType", Schema = "ttb")]
    public partial class TTBActionType
    {
        [Key]
        public int TTBActionTypeId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Action { get; set; }
        [StringLength(20)]
        public string ActionName { get; set; }
        public int? AccountStatusId { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}