// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TTB.BankAccountConsent.Models
{
    [Table("TTBBatchTrailer", Schema = "ttb")]
    public partial class TTBBatchTrailer
    {
        [Key]
        public Guid TTBBatchTrailerId { get; set; }
        public Guid? TTBBatchHeaderId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string RecodeType { get; set; }
        [StringLength(6)]
        [Unicode(false)]
        public string LastSequenceNo { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string BankCode { get; set; }
        public int? TotalAddApplyRecords { get; set; }
        public int? TotalCancelRecords { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string Spare { get; set; }
        [Unicode(false)]
        public string PlainText { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}