// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TTB.BankAccountConsent.Models
{
    [Table("TTBBatchDetail", Schema = "ttb")]
    public partial class TTBBatchDetail
    {
        [Key]
        public Guid TTBBatchDetailId { get; set; }
        public Guid? TTBBatchHeaderId { get; set; }
        public int? Seq { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string RecodeType { get; set; }
        [StringLength(6)]
        [Unicode(false)]
        public string SequenceNo { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string BankCode { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Action { get; set; }
        public DateTime? ApplyDate { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Ref1 { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Ref2 { get; set; }
        [StringLength(16)]
        [Unicode(false)]
        public string AccountNo { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AccountName { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string ChannelApply { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Status { get; set; }
        [StringLength(64)]
        [Unicode(false)]
        public string Spare { get; set; }
        [Unicode(false)]
        public string PlainText { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}