// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TTB.BankAccountConsent.Models
{
    [Table("TTBBatchHeader", Schema = "ttb")]
    public partial class TTBBatchHeader
    {
        [Key]
        public Guid TTBBatchHeaderId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string RecordType { get; set; }
        [StringLength(6)]
        [Unicode(false)]
        public string SequenceNo { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string BankCode { get; set; }
        [StringLength(4)]
        [Unicode(false)]
        public string CompId { get; set; }
        [StringLength(40)]
        [Unicode(false)]
        public string CompanyName { get; set; }
        public DateTime? PostDateTime { get; set; }
        [StringLength(131)]
        [Unicode(false)]
        public string Spare { get; set; }
        [Unicode(false)]
        public string PlainText { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}