// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TTB.BankAccountConsent.Models;

namespace TTB.BankAccountConsent.Data
{
    public partial class AppDBContext
    {
        private IAppDBContextProcedures _procedures;

        public virtual IAppDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AppDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAppDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usp_TTBBatchToBankAccountConsent_InsertResult>().HasNoKey().ToView(null);
        }
    }

    public partial class AppDBContextProcedures : IAppDBContextProcedures
    {
        private readonly AppDBContext _context;

        public AppDBContextProcedures(AppDBContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_TTBBatchToBankAccountConsent_InsertResult>> usp_TTBBatchToBankAccountConsent_InsertAsync(Guid? BatchHeaderId, string FileName, string LocalPath, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BatchHeaderId",
                    Value = BatchHeaderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "FileName",
                    Size = 200,
                    Value = FileName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LocalPath",
                    Size = -1,
                    Value = LocalPath ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_TTBBatchToBankAccountConsent_InsertResult>("EXEC @returnValue = [ttb].[usp_TTBBatchToBankAccountConsent_Insert] @BatchHeaderId, @FileName, @LocalPath", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
