// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TTB.BankAccountConsent.Models;

namespace TTB.BankAccountConsent.Data
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<usp_TTBBatchToBankAccountConsent_InsertResult>> usp_TTBBatchToBankAccountConsent_InsertAsync(Guid? BatchHeaderId, string FileName, string LocalPath, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
